name: lakehouse_demo
version: "1.0.0"
config-version: 2

profile: lakehouse_demo

model-paths:
  - models

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  lakehouse_demo:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: mart