version: 2
models:
  - name: stg_users
    columns:
      - name: user_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]
  - name: stg_events
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]
