apiVersion: batch/v1
kind: Job
metadata:
  name: hive-schema-init
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: hive-schema-init
    spec:
      containers:
      - name: hive-schema-init
        image: hive-metastore:3.0.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          /opt/hive-metastore/bin/schematool --verbose -initSchema -dbType postgres \
          -driver org.postgresql.Driver -userName "hive" -passWord "hive" \
          -url "jdbc:postgresql://hms-postgresql.metastore.svc.cluster.local:5432/metastore?user=hive&password=hive&createDatabaseIfNotExist=true"
      restartPolicy: Never