name: dbt_spark_iceberg_demo
version: "1.0.0"
config-version: 2
profile: dbt_spark_iceberg_demo
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  dbt_spark_iceberg_demo:
    +file_format: iceberg
    +catalog: iceberg
    +schema: demo
    staging: {+materialized: view}
    intermediate: {+materialized: ephemeral}
    marts:
      +materialized: table
      +tblproperties: {"format-version": "2", "write.format.default": parquet}
seeds:
  dbt_spark_iceberg_demo:
    +schema: raw
    +quote_columns: false
snapshots:
  dbt_spark_iceberg_demo:
    +target_schema: snapshots
