lakehouse_demo:
  target: dev

  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('KYUUBI_HOST', 'kyuubi-thrift-binary.kyuubi.svc.cluster.local') }}"
      port: "{{ env_var('KYUUBI_PORT', '10009') | int }}"
      user: "sy"
      password: "UserPassword"
      auth: LDAP
      schema: default
      threads: 2
      connect_timeout: 30
      connect_retries: 3